* What
Simulation of micro-swimmers with brownian motion.

Originally I implemented this as part of an assignment for a simulation course,
but in python with pygame and numpy. This reimplementation is written in C with
CUDA and OpenGL and serves as an exploration project for particle physics simulation.

* Todos
- Tiling subregions for better performance than bruteforce n-body
    - Also launch more than one thread block to not be capped to 1024 particles
- FPS counter
- Separate simulation and rendering threads
- Collision and accurate particle size rendering

* References
- CUDA particle simulation :: https://developer.download.nvidia.com/assets/cuda/files/particles.pdf
- Brownian motion simulation :: Volpe, Gigan & Volpe (2014) Simulation of the active Brownian motion of a microswimmer, American Journal of Physics.
- Metastable clusters and channels :: Nilsson & Volpe (2017) Metastable clusters and channels formed by active particles with aligning interactions, New Journal of Physics.
