#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PARTICLES_CAPACITY 1024

#define RNG_SEED 1234

#define TRANS_COEFF 0.01f
#define ROT_COEFF 0.01f
#define DELTA_T 0.01f
#define INTR_CUTOFF 25.0f
#define ATTR_STRENGTH 20.0f
#define ACTIVE_FRACTION 0.2f
#define PARTICLE_SPEED 100.0f
#define PARTICLE_RADIUS 5.0f

#define LOOP_AROUND

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#endif /* CONSTANTS_H */
