#ifndef CONSTANTS_H
#define CONSTANTS_H

#define PARTICLES_CAPACITY 1024

#define RNG_SEED 1234

#define TRANS_COEFF 0.22f
#define ROT_COEFF 0.16f
#define DELTA_T 0.01f
#define INTR_CUTOFF 80.0f
#define ATTR_STRENGTH 5.0f

#define LOOP_AROUND

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

#endif /* CONSTANTS_H */
